#undef BOND_STANCE_DIRECTORY

#ifdef BONDS_EVOLUTION_FROZEN
#undef BONDS_EVOLUTION_FROZEN
#endif

#undef BOND_WARMTH_MIN
#undef BOND_WARMTH_MAX
#undef BOND_WEIGHT_MIN
#undef BOND_WEIGHT_MAX

#undef BOND_MAX_PER_MIND
#undef BOND_COMMIT_COOLDOWN
#undef BOND_MAX_HISTORY
#undef BOND_VISIBLE_WEIGHT

#undef BOND_COMMIT_FALLOFF
#undef BOND_KILL_ATTRIBUTION_WINDOW

#undef BOND_TAG_NONE
#undef BOND_TAG_SHED_BLOOD
#undef BOND_TAG_KILLED_ME
#undef BOND_TAG_KILLED_THEM
#undef BOND_TAG_COMFORTED
#undef BOND_TAG_SERVED_TOGETHER
#undef BOND_TAG_OWES_DEBT

#undef BOND_MAX_SEEDS
#undef BOND_SEED_DELAY
#undef BOND_SEED_RETRY

#undef BOND_CATEGORY_VIOLENCE
#undef BOND_CATEGORY_KINDNESS
#undef BOND_CATEGORY_DEATH
#undef BOND_CATEGORY_SEED
#undef BOND_CATEGORY_DREAM

#undef BOND_MURDER_WINDOW

#undef BOND_DREAM_CHANCE_OWN_NEGATIVE
#undef BOND_DREAM_CHANCE_FOREIGN_NEGATIVE
#undef BOND_DREAM_CHANCE_OWN_POSITIVE
#undef BOND_DREAM_CHANCE_FOREIGN_POSITIVE

#undef BOND_DREAM_POSITIVE
#undef BOND_DREAM_NEGATIVE

#undef BOND_DREAM_ECHO_SCALE

#undef BOND_DREAM_VAMPIRE_NONE
#undef BOND_DREAM_VAMPIRE_OTHER
#undef BOND_DREAM_VAMPIRE_DREAMER

#undef BOND_DREAM_SCOPE_OWN
#undef BOND_DREAM_SCOPE_FOREIGN
#undef BOND_DREAM_SCOPE_ANY

#undef BOND_ARCH_WARRIOR
#undef BOND_ARCH_LAWMAN
#undef BOND_ARCH_DEVOUT
#undef BOND_ARCH_NOBLE
#undef BOND_ARCH_SCHOLAR
#undef BOND_ARCH_HEALER
#undef BOND_ARCH_CRAFTER
#undef BOND_ARCH_MERCHANT
#undef BOND_ARCH_OUTLAW
#undef BOND_ARCH_SERVILE
#undef BOND_ARCH_WANDERER
#undef BOND_ARCH_UNDEAD

#undef BOND_LOOSE_BLOC
#undef BOND_FACTION_NOBLE
#undef BOND_FACTION_COURT
#undef BOND_FACTION_RETINUE
#undef BOND_FACTION_GARRISON
#undef BOND_FACTION_CITYWATCH
#undef BOND_FACTION_VANGUARD
#undef BOND_FACTION_CHURCH
#undef BOND_FACTION_INQUISITION
#undef BOND_FACTION_BURGHER
#undef BOND_FACTION_ATC
#undef BOND_FACTION_PEASANT
#undef BOND_FACTION_SIDEFOLK
#undef BOND_FACTION_WANDERER
#undef BOND_FACTION_SLAVE
#undef BOND_FACTION_OUTLAW

#undef BOND_STANCE_SAME_FACTION_WARMTH
#undef BOND_STANCE_AFFINITY_THRESHOLD
#undef BOND_MAP_MIN_WEIGHT
#undef BOND_SHARE_ROLE
#undef BOND_SHARE_LORE
#undef BOND_SHARE_STORYTELLER
#undef BOND_SHARE_ZONE
#undef BOND_SHARE_MAP
#undef BOND_MAX_SWING
#undef BOND_SWING_WINDOW
#undef BOND_HOUSE_PROPAGATION
#undef BOND_INFLUENCE_POOL
#undef BOND_INFLUENCE_BAN
#undef BOND_INFLUENCE_REFILL

#undef BOND_KIN_PARENT
#undef BOND_KIN_CHILD
#undef BOND_KIN_SPOUSE
#undef BOND_KIN_FORMER_SPOUSE
#undef BOND_KIN_SWORN_SIBLING

#undef BOND_GROUP_FAMILY
#undef BOND_GROUP_KNOWN
#undef BOND_GROUP_WARM
#undef BOND_GROUP_COLD
#undef BOND_GROUP_HOSTILE

#undef BONDLOG_DEBUG
#undef BONDLOG_INFO
#undef BONDLOG_WARN
#undef BONDLOG_ERROR

#ifdef BONDS_DEBUG_LOGGING
#undef BONDS_DEBUG_LOGGING
#endif
