#define CONTRACTOR_LEVEL_SLEEPING 0
#define CONTRACTOR_LEVEL_AWAKENED 1
#define CONTRACTOR_LEVEL_AWARE 2
#define CONTRACTOR_LEVEL_WATCHFUL 3
#define CONTRACTOR_LEVEL_COMPLETE 4


#define CONTRACTOR_LEVEL_LESSER CONTRACTOR_LEVEL_SLEEPING
#define CONTRACTOR_LEVEL_CONTRACTEE CONTRACTOR_LEVEL_AWAKENED
#define CONTRACTOR_LEVEL_VELVET CONTRACTOR_LEVEL_AWARE
#define CONTRACTOR_LEVEL_GREATER CONTRACTOR_LEVEL_WATCHFUL
#define CONTRACTOR_LEVEL_UNBOUND CONTRACTOR_LEVEL_COMPLETE

#define CONTRACTOR_CONTRACT_DRAFT "draft"
#define CONTRACTOR_CONTRACT_PENDING_CONTRACTOR "pending_contractor"
#define CONTRACTOR_CONTRACT_PENDING_CONTRACTEE "pending_contractee"
#define CONTRACTOR_CONTRACT_ACTIVE "active"
#define CONTRACTOR_CONTRACT_FULFILLED "fulfilled"
#define CONTRACTOR_CONTRACT_BROKEN "broken"
#define CONTRACTOR_CONTRACT_CANCELLED "cancelled"

#define CONTRACTOR_LUX_UNOWNED 1
#define CONTRACTOR_LUX_PERSONAL 2
#define CONTRACTOR_LUX_PREPARED 3

#define CONTRACTOR_DEFAULT_DEVOTION 100
#define CONTRACTOR_DEFAULT_MAX_DEVOTION 200
#define CONTRACTOR_DEVOTION_COLOR "#8B003C"
#define CONTRACTOR_DEFAULT_SUBMISSION_THRESHOLD 100

#define CONTRACTOR_DEVOTION_MINUTE_DRAIN 5
#define CONTRACTOR_TRUE_FORM_MINUTE_DRAIN 1
#define CONTRACTOR_ABILITY_DEVOTION_COST 5
#define CONTRACTOR_CONTRACT_DEVOTION_GAIN 100

#define CONTRACTOR_LOOSE_LUX_BASE_POWER 50
#define CONTRACTOR_LOOSE_LUX_LEVEL_PENALTY 5
#define CONTRACTOR_MOB_LUX_BASE_POWER 100
#define CONTRACTOR_MOB_LUX_LEVEL_BONUS 10
#define CONTRACTOR_SUBMITTED_DEVOTION_GAIN 20
#define CONTRACTOR_SUBMITTED_LUX_POWER_GAIN 10
#define CONTRACTOR_SUBMITTED_DEVOTION_DECAY 4
#define CONTRACTOR_SUBMITTED_LUX_DECAY 2
#define CONTRACTOR_RETURN_TO_SUMMON_DURATION (30 MINUTES)

#define CONTRACTOR_TRUE_FORM_COLOR "#8B003C"
#define CONTRACTOR_TRUE_FORM_OUTLINE "#D24C8E"
#define CONTRACTOR_TRUE_FORM_FILTER_SIZE 1

#define CONTRACTOR_TRUE_FORM_ICON 'modular_twilight_axis/icons/roguetown/mob/monster/tempress.dmi'
#define CONTRACTOR_TRUE_FORM_ICON_STATE "tempress"
#define CONTRACTOR_TRUE_FORM_USE_WILDSHAPE_BODY TRUE
#define CONTRACTOR_TRUE_FORM_PIXEL_X 0
#define CONTRACTOR_TRUE_FORM_PIXEL_Y 0
#define CONTRACTOR_TRUE_FORM_TRAIT_SOURCE "contractor_true_form_body"

#define CONTRACTOR_EMBRACE_TRAIT_SOURCE "contractor_true_form_embrace"
#define CONTRACTOR_EMBRACE_PULSE_CD (1 SECONDS)
#define CONTRACTOR_EMBRACE_GAIN_CD (3 SECONDS)
#define CONTRACTOR_EMBRACE_RANGE 2
#define CONTRACTOR_ENTITY_ERP_TRAINING_XP 2

#define CONTRACTOR_SEAL_CHECK_RANGE 0
#define CONTRACTOR_SEAL_BASE_POWER 20
#define CONTRACTOR_SEAL_ARCANA_POWER 20
#define CONTRACTOR_SEAL_DECAY_INTERVAL (10 SECONDS)
#define CONTRACTOR_SEAL_BASE_DECAY 1
#define CONTRACTOR_SEAL_CONTRACT_DECAY 0.5

#define CONTRACTOR_CONSENT_REQUIRED TRUE
#define CONTRACTOR_CONSENT_NOT_REQUIRED FALSE

#define CONTRACTOR_DRINK_DIMINISH_STEP 0.15
#define CONTRACTOR_DRINK_DIMINISH_FLOOR 0.15

#define CONTRACTOR_CONTRACT_REFUSAL_LUX_PENALTY 30
#define CONTRACTOR_CONTRACT_INFORMATION_CONFIRM_TIME (10 MINUTES)
#define CONTRACTOR_BODY_CHANGE_PERMISSION_TIME (5 MINUTES)
#define CONTRACTOR_SUBMISSION_THRESHOLD 100

#ifndef CONTRACTOR_TRAIT_SOURCE
#define CONTRACTOR_TRAIT_SOURCE "contractor_contracts"
#endif
#ifndef COMSIG_MOB_PARRY_SUCCESS
#define COMSIG_MOB_PARRY_SUCCESS "mob_parry_success"
#endif
#ifndef COMSIG_ATTACK_TRY_CONSUME
#define COMSIG_ATTACK_TRY_CONSUME "attack_try_consume"
#endif

#ifndef COMSIG_SEX_RECEIVE_ACTION
#define COMSIG_SEX_RECEIVE_ACTION "sex_receive_action"
#endif

#ifndef COMSIG_MOB_DODGE_SUCCESS
#define COMSIG_MOB_DODGE_SUCCESS "mob_dodge_success"
#endif



#ifndef COMSIG_MOB_SAY
#define COMSIG_MOB_SAY "mob_say"
#endif

#ifndef COMSIG_MOB_EAT
#define COMSIG_MOB_EAT "mob_eat"
#endif
#ifndef COMSIG_MOB_SLEEP
#define COMSIG_MOB_SLEEP "mob_sleep"
#endif
#ifndef COMSIG_SEX_CLIMAX
#define COMSIG_SEX_CLIMAX "sex_climax"
#endif


#ifndef COMSIG_ITEM_EQUIPPED
#define COMSIG_ITEM_EQUIPPED "item_equipped"
#endif
#ifndef COMSIG_ITEM_DROPPED
#define COMSIG_ITEM_DROPPED "item_dropped"
#endif
#ifndef COMSIG_CONTRACTOR_ITEM_EQUIPPED
#define COMSIG_CONTRACTOR_ITEM_EQUIPPED "contractor_item_equipped"
#endif
#ifndef COMSIG_CONTRACTOR_ITEM_DROPPED
#define COMSIG_CONTRACTOR_ITEM_DROPPED "contractor_item_dropped"
#endif
#ifndef COMSIG_PARENT_QDELETING
#define COMSIG_PARENT_QDELETING "parent_qdeleting"
#endif
#define CONTRACTOR_PASSIVE_ITEM_TRAIT_SOURCE "contractor_passive_item"

#define CONTRACTOR_EFFECT_BASE_DURATION (10 SECONDS)
#define CONTRACTOR_EFFECT_LEVEL_DURATION (5 SECONDS)
#define CONTRACTOR_STEALTH_REFRESH_INTERVAL (1 SECONDS)

#define CONTRACTOR_CONTRACT_SEAL_LUX_COST 100
#define CONTRACTOR_CONTRACT_LEFTOVER_TO_LUX_RATIO 5
#define CONTRACTOR_ATTACK_TRIGGER_CHANCE_MIN 5
#define CONTRACTOR_ATTACK_TRIGGER_CHANCE_MAX 100
#define CONTRACTOR_CURSE_SEX_PHASE_START "start"
#define CONTRACTOR_CURSE_SEX_PHASE_PROCESS "process"
#define CONTRACTOR_CURSE_SEX_PHASE_BOTH "both"
#define CONTRACTOR_CLIMAX_SOURCE_ANY "any"
