/datum/outfit/job/roguetown/gnoll/berserker/post_equip(mob/living/carbon/human/H)
	..()
	if(H.mind)
		spawn(1)
			if(H.mind)
				H.change_stat(STATKEY_STR, 2)
				H.change_stat(STATKEY_PER, 1)
				H.change_stat(STATKEY_INT, -1)
				H.change_stat(STATKEY_CON, 1)
				H.change_stat(STATKEY_WIL, 1)
				H.change_stat(STATKEY_SPD, 1)
				H.change_stat(STATKEY_LCK, -1)
		H.mind?.RemoveSpell(/obj/effect/proc_holder/spell/invoked/invisibility/gnoll)

/datum/outfit/job/roguetown/gnoll_impure/post_equip(mob/living/carbon/human/H)
	..()
	if(H.mind)
		spawn(1)
			if(H.mind)
				H.change_stat(STATKEY_STR, 3)
				H.change_stat(STATKEY_PER, 0)
				H.change_stat(STATKEY_INT, 0)
				H.change_stat(STATKEY_CON, 0)
				H.change_stat(STATKEY_WIL, 1)
				H.change_stat(STATKEY_SPD, 0)
				H.change_stat(STATKEY_LCK, 0)

/datum/outfit/job/roguetown/gnoll/knight/post_equip(mob/living/carbon/human/H)
	..()
	if(H.mind)
		spawn(1)
			if(H.mind)
				H.change_stat(STATKEY_STR, 3)
				H.change_stat(STATKEY_PER, 0)
				H.change_stat(STATKEY_INT, 0)
				H.change_stat(STATKEY_CON, 1)
				H.change_stat(STATKEY_WIL, 1)
				H.change_stat(STATKEY_SPD, -1)
				H.change_stat(STATKEY_LCK, 0)
		H.mind?.RemoveSpell(/obj/effect/proc_holder/spell/invoked/invisibility/gnoll)

/datum/outfit/job/roguetown/gnoll/shaman/post_equip(mob/living/carbon/human/H)
	..()
	if(H.mind)
		spawn(1)
			if(H.mind)
				H.change_stat(STATKEY_STR, 2)
				H.change_stat(STATKEY_PER, 0)
				H.change_stat(STATKEY_INT, 0)
				H.change_stat(STATKEY_CON, 1)
				H.change_stat(STATKEY_WIL, 1)
				H.change_stat(STATKEY_SPD, 0)
				H.change_stat(STATKEY_LCK, 0)

/datum/outfit/job/roguetown/gnoll/templar/post_equip(mob/living/carbon/human/H)
	..()
	if(H.mind)
		spawn(1)
			if(H.mind)
				H.change_stat(STATKEY_STR, 2)
				H.change_stat(STATKEY_PER, 0)
				H.change_stat(STATKEY_INT, 0)
				H.change_stat(STATKEY_CON, 2)
				H.change_stat(STATKEY_WIL, 3)
				H.change_stat(STATKEY_SPD, 1)
				H.change_stat(STATKEY_LCK, 0)
